<?php
    session_start();
    $api = "rzp_test_1A2WrZBXRvjKNx";
    $amount = $_SESSION['Razorpay']*100;
    $Name = $_SESSION['namee'];
    $Email = $_SESSION['usermail'];
?>

<form action="email.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key= "<?php echo $api;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="1"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Celesial Palace"
    data-description="Book your rooom"
    data-image="https://images.app.goo.gl/iqVoqzt118vAUfnb7"
    data-prefill.name="<?php echo $Name;?>"
    data-prefill.email="<?php echo $Email;?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>